# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    front.success_uri: '%env(FRONT_SUCCESS_URI)%'
    front.error_uri: '%env(FRONT_ERROR_URI)%'
    blizzard.region: '%env(BLIZZARD_REGION)%'
    blizzard.locale: '%env(BLIZZARD_LOCALE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DTO/'

    App\Security\Voter\:
        resource: '../src/Security/Voter'
        tags: ['security.voter']
        autowire: true
        autoconfigure: true

    App\Service\TokenEncryptionService:
        arguments:
             $appSecret: '%env(APP_SECRET)%'

    App\Service\BlizzardService:
        arguments:
            $blizzardRegion: '%env(BLIZZARD_REGION)%'
            $blizzardLocale: '%env(BLIZZARD_LOCALE)%'
            $blizzardClientId: '%env(OAUTH_BNET_CLIENT_ID)%'
            $blizzardClientSecret: '%env(OAUTH_BNET_CLIENT_SECRET)%'

    App\Command\GetBlizzardRealmCommand:
        arguments:
            $blizzardClientId: '%env(OAUTH_BNET_CLIENT_ID)%'
            $blizzardClientSecret: '%env(OAUTH_BNET_CLIENT_SECRET)%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
