



parameters:
    front.success_uri: '%env(FRONT_SUCCESS_URI)%'
    front.error_uri: '%env(FRONT_ERROR_URI)%'
    blizzard.region: '%env(BLIZZARD_REGION)%'
    blizzard.locale: '%env(BLIZZARD_LOCALE)%'

services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DTO/'

    App\Security\Voter\:
        resource: '../src/Security/Voter'
        tags: ['security.voter']
        autowire: true
        autoconfigure: true

    App\Service\TokenEncryptionService:
        arguments:
             $appSecret: '%env(APP_SECRET)%'

    App\Service\BlizzardService:
        arguments:
            $blizzardRegion: '%env(BLIZZARD_REGION)%'
            $blizzardLocale: '%env(BLIZZARD_LOCALE)%'
            $blizzardClientId: '%env(OAUTH_BNET_CLIENT_ID)%'
            $blizzardClientSecret: '%env(OAUTH_BNET_CLIENT_SECRET)%'

    App\Command\GetBlizzardRealmCommand:
        arguments:
            $blizzardClientId: '%env(OAUTH_BNET_CLIENT_ID)%'
            $blizzardClientSecret: '%env(OAUTH_BNET_CLIENT_SECRET)%'

    App\Command\GetBlizzardTokenCommand:
        arguments:
            $blizzardClientId: '%env(OAUTH_BNET_CLIENT_ID)%'
            $blizzardClientSecret: '%env(OAUTH_BNET_CLIENT_SECRET)%'


