
framework:
    secret: '%env(APP_SECRET)%'

    session:
        name: APP_SESSION
        handler_id: null
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: lax
        cookie_lifetime: 3600  # 1 hour
        gc_maxlifetime: 3600



when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
